---
title: "Midterm project"
output:
  word_document: default
  pdf_document: default
date: "2022-11-06"
author: "Yaquan Yang"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(readxl)
library(dplyr)
library(gmodels)
library(Rmisc)
```

```{r}
strawb <- read_xlsx("strawberries-2022oct30-a.xlsx",col_names = TRUE)
head(strawb)
```
### Get the column names and index them
```{r}
cnames <- colnames(strawb)
x <- 1:dim(strawb)[2]
```

## Drop null columns

```{r message=F,warning=F}
dim(strawb)
drop_cols<-sapply(strawb,function(x) length(unique(x))==1)
drop_cols<-names(drop_cols)[drop_cols]
strawb %<>% dplyr::select(!all_of(drop_cols))
dim(strawb)
```


## Separate “Data Item” column

```{r message=F,warning=F}
strawb<- strawb %>% separate(col=`Data Item`,
                    into = c("type", "measure"),
                    sep = ", MEASURED IN ",
                    fill = "warn")
```					

## about sales

```{r message=F,warning=F}
#table(strawb$type)

plot1.data<-strawb %>% 
           filter(type=='STRAWBERRIES, ORGANIC - SALES',
				  measure=='$',
                  Year==2016,
                  str_detect(Value,'^\\d+$')) %>%
		   mutate(Value=as.numeric(Value),
		          Year=as.character(Year))
				

#plot1.data


ggplot(plot1.data,aes(x=reorder(State,Value),y=Value))+
    geom_bar(stat='identity',position='dodge2',fill='pink',colour='#34282C',width=0.65)+
    theme_bw()+
    scale_y_continuous(trans='log10')+
    labs(x='',y='STRAWBERRIES, ORGANIC - SALES',
    title='STRAWBERRIES, ORGANIC - SALES, 2016')
```

## about price

```{r message=F,warning=F,fig.width=9.3}

#table(strawb$type)


plot3.data<-strawb %>% 
             filter(type=='STRAWBERRIES - PRICE RECEIVED') %>%
			 mutate(Value=as.numeric(Value),
			       Year=as.character(Year))
			 
			 
			 
ggplot(plot3.data,aes(y=State,x=Year,size=Value,fill=State))+
   geom_point(shape=21)+
   theme_bw()+
   geom_text(aes(label=Value),size=4,nudge_y=0.2)+
   scale_size_continuous(range=c(2,16))+
   labs(size='PRICE RECEIVED',title='STRAWBERRIES - PRICE RECEIVED')
```

## about chemical 

```{r message=F,warning=F,fig.width=9.3}
plot2.data<-strawb %>% 
            filter(
			str_detect(`Domain Category`,'TOTAL'),
			State=='CALIFORNIA',
			str_detect(Value,'^\\d+$'),
			) %>%
			mutate(Value=as.numeric(Value),
			       Year=as.character(Year),
				   Domain=ordered(Domain,c('CHEMICAL, HERBICIDE','CHEMICAL, INSECTICIDE','CHEMICAL, FUNGICIDE','CHEMICAL, OTHER')))
			
			
ggplot(plot2.data,aes(x=Year,y=Value,fill=Domain))+
  geom_bar(stat='identity',position='dodge')+
  theme_bw()+
  scale_fill_hue()+
  labs(title='CHEMICAL usage in California')
```



## About Gradescope Questions
## Q2 
```{r}
Cal_organic_2016 <- strawb %>% filter(State=="CALIFORNIA",Year==2016,str_detect(`type`,"(ORGANIC - SALES)"))
# Cal_organic_2016 <- strawb %>% filter(State=="CALIFORNIA",Year==2016,Domain=="ORGANIC STATUS")

# We choose "ORGANIC - SALES, MEASURED IN $" for computing
Sales_value <-231304956
cv <- 0.137
mean <- Sales_value
sd <- cv*mean
upper <- mean+1.96*sd
lower <- mean-1.96*sd
upper
lower
```
## Q3 
```{r}
filter <- filter(strawb, State == 'CALIFORNIA' & Year == 2016 & Domain != 'ORGANIC STATUS')
Cal_non_organic_2016 <- filter(filter, Value != "(NA)" & Value != "(D)" & Domain != "TOTAL")

Value <- as.numeric(Cal_non_organic_2016$Value)

# Since we don't have the value of CV(%) for the "Cal_non_organic_2016" data, we can not compute the 95% CI of non-organic strawberry sales
```
## Q4
```{r}
chemical <- filter(strawb,str_detect(`Domain Category`,"(CHEMICAL|FERTILIZER)"))

n_distinct(chemical$`Domain Category`)
# Chemicals=175
```


## Q5
```{r}
chemical_florida <- filter(strawb,str_detect(`Domain Category`,"(CHEMICAL|FERTILIZER)"), State=="FLORIDA")
chemical_california <- filter(strawb,str_detect(`Domain Category`,"(CHEMICAL|FERTILIZER)"), State=="CALIFORNIA")
n_distinct(chemical_california$`Domain Category`)-n_distinct(chemical_florida$`Domain Category`)
#so the difference is 138 - 115=23
```

